n1 = int(input('digite um numero'))
n2 = int(input('digite um numero'))
s = n1+n2
# print('a soma vale', s)
# print('as variaveis sao: int; float, bool, str')
# print('a soma vale {}'.format(s))
# print('{}'.format(n1), type(n1))
# print(n1, type(n1))
# print(n2, type(n2))
print('os valores de {} e {} são respectivamente "{}" e "{}"'.format(n1, n2, type(n1), type(n2)))
# print('a soma entre', n1, 'e', n2, 'vale', s)
print('a soma entre {} e {} vale {}'.format(n1, n2, s))
