n = int(0)
input()
print()
# int, float, bool, str
print('asdasd {}' .format(n))
type(n)

# n01 = str(n.isascii())
# n02 = str(n.isnumeric())
# n03 = str(n.isalpha())
# n04 = str(n.isalnum())
# n05 = str(n.isdigit())
# n06 = str(n.isdecimal())
# n07 = str(n.isidentifier())
# n08 = str(n.islower())
# n09 = str(n.isprintable())
# n10 = str(n.isspace())
# n11 = str(n.istitle())
# n12 = str(n.isupper())
